name: "CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: 'ubuntu-20.04'
    name: Nix Flake Check
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Add Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v1
      - name: Check flake
        run: |
          nix flake check
          nix build .#tests   # we want to capture an output path, this build should be cached already
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: result/share/test/coverage.out